# Generated by Django 5.2.12 on 2026-04-12 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="decks", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "flashcards_deck",
                "constraints": [models.UniqueConstraint(fields=("name", "owner"), name="unique_deck_user_name")],
            },
        ),
    ]
