# Generated by Django 5.2.12 on 2026-04-12 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("decks", "0002_initial"),
        ("flashcards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flashcards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="flashcards", to="decks.deck"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="flashcard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="flashcards.flashcard"
            ),
        ),
        migrations.AddField(
            model_name="flashcarduserstate",
            name="flashcard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="flashcard_states", to="flashcards.flashcard"
            ),
        ),
        migrations.AddField(
            model_name="flashcarduserstate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcard_states",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="flashcard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="flashcards.flashcard"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="flashcard",
            constraint=models.UniqueConstraint(
                fields=("question", "created_by", "deck"), name="unique_flashcard_created_by_question_deck"
            ),
        ),
        migrations.AddConstraint(
            model_name="flashcarduserstate",
            constraint=models.UniqueConstraint(fields=("flashcard", "user"), name="unique_flashcard_user_state"),
        ),
    ]
