# Generated by Django 5.2.12 on 2026-04-13 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcarduserstate",
            name="flashcard",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="flashcard_state", to="flashcards.flashcard"
            ),
        ),
        migrations.AlterField(
            model_name="flashcarduserstate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="flashcard_state", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
