# Generated by Django 5.2.12 on 2026-04-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0002_alter_review_deck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="deck",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="flashcards", to="flashcards.deck"
            ),
        ),
    ]
