# Generated by Django 5.2.12 on 2026-04-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0002_alter_flashcarduserstate_flashcard_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcarduserstate",
            name="last_reviewed_at",
            field=models.DateTimeField(auto_now=True, default="2026-04-14 00:00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flashcarduserstate",
            name="next_review_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
