# Generated by Django 5.2.12 on 2026-04-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0003_alter_flashcard_deck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="deck",
            field=models.ManyToManyField(blank=True, related_name="flashcards", to="flashcards.deck"),
        ),
    ]
