# Generated by Django 5.2.12 on 2026-04-09 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_m2m_decks_to_fk(apps, schema_editor):
    Flashcard = apps.get_model("flashcards", "Flashcard")
    Deck = apps.get_model("flashcards", "Deck")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)

    fallback_user = User.objects.order_by("id").first()

    for flashcard in Flashcard.objects.all().iterator():
        deck_id = flashcard.deck.values_list("id", flat=True).first()
        if deck_id:
            flashcard.deck_fk_id = deck_id
            flashcard.save(update_fields=["deck_fk"])
            continue

        owner_id = flashcard.created_by_id
        if owner_id is None and fallback_user is not None:
            owner_id = fallback_user.id

        if owner_id is None:
            raise RuntimeError(
                "Cannot migrate flashcard without deck: no owner user exists."
            )

        fallback_deck, _ = Deck.objects.get_or_create(
            name="Migrated Deck", owner_id=owner_id
        )
        flashcard.deck_fk_id = fallback_deck.id
        flashcard.save(update_fields=["deck_fk"])


def reverse_copy_m2m_decks_to_fk(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0004_alter_flashcard_deck"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deck",
            name="members",
        ),
        migrations.AddField(
            model_name="flashcard",
            name="deck_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcards",
                to="flashcards.deck",
            ),
        ),
        migrations.RunPython(copy_m2m_decks_to_fk, reverse_copy_m2m_decks_to_fk),
        migrations.RemoveField(
            model_name="flashcard",
            name="deck",
        ),
        migrations.RenameField(
            model_name="flashcard",
            old_name="deck_fk",
            new_name="deck",
        ),
    ]
