# Generated by Django 5.2.12 on 2026-04-09 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0006_alter_flashcard_deck"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="flashcard",
            constraint=models.UniqueConstraint(
                fields=("question", "created_by", "deck"),
                name="unique_flashcard_created_by_question_deck",
            ),
        ),
    ]
