# Generated by Django 5.2.12 on 2026-04-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_alter_flashcard_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='deck',
        ),
    ]
