# Generated by Django 5.2.12 on 2026-04-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_flashcard_unique_flashcard_created_by_question_deck'),
        ('flashcards', '0007_remove_review_deck'),
    ]

    operations = [
    ]
