# Generated by Django 5.2.13 on 2026-04-11 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0009_move_deck_to_decks_app"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flashcard",
            name="answer_a",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="answer_b",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="answer_c",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="answer_d",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="correct_answer",
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="flashcards.flashcard",
                    ),
                ),
            ],
        ),
    ]
